version: 2
updates:
  - package-ecosystem: "swift"
    directories:
      - "/"
      - "/Examples/CustomRepeatDateSample/CustomRepeatDateSample.xcodeproj/project.xcworkspace/xcshareddata/swiftpm"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Tokyo"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Tokyo"
