name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  tests:
    runs-on: macOS-26
    timeout-minutes: 10
    strategy:
      matrix:
        xcode:
          - '26.0'
    steps:
      - uses: actions/checkout@v3

      - name: Select Xcode ${{ matrix.xcode }}
        run: |
          sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode }}.app
          xcrun simctl list > /dev/null

      - name: Run test
        run: |
          xcodebuild test -scheme CustomRepeatDate -destination platform="iOS Simulator,name=iPhone 17 Pro"
